# Generated by Django 2.1 on 2019-01-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='image',
            field=models.ImageField(upload_to='./static/upload/type', verbose_name='商品类型图片'),
        ),
        migrations.AlterModelTable(
            name='indextypegoodsbanner',
            table='df_index_type_goods',
        ),
    ]
