# Generated by Django 2.1 on 2019-01-02 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190102_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsimage',
            options={'verbose_name_plural': '商品图片'},
        ),
        migrations.AlterModelTable(
            name='goodsimage',
            table='df_goods_image',
        ),
    ]
