# Generated by Django 2.1 on 2019-01-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190102_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodssku',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='商品销量'),
        ),
    ]
