# Generated by Django 2.1 on 2019-01-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_goodssku_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='商品价格'),
        ),
    ]
