# Generated by Django 2.1 on 2019-01-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190108_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_status',
            field=models.CharField(choices=[(0, '待支付'), (1, '待发货'), (2, '待收货'), (3, '待评价'), (4, '已完成')], default=1, max_length=32, verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='trade_no',
            field=models.CharField(default='', max_length=128, verbose_name='支付编号'),
        ),
    ]
