# Generated by Django 2.1 on 2019-01-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190125_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='transit_price',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=32, verbose_name='运费'),
        ),
    ]
