# Generated by Django 2.1 on 2019-01-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190125_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='transit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=32, verbose_name='运费'),
        ),
    ]
