# Generated by Django 2.1 on 2019-01-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190125_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '待发货'), (3, '待收货'), (4, '待评价'), (5, '已完成')], default=1, max_length=32, verbose_name='支付状态'),
        ),
    ]
